### ISSUE TITLE
Alternative meaning for `contributors` function

### ISSUE THREAD

**Issue by astrieanna** [WestleyArgentum/GitHub.jl#15]
Currently, you have a function named `contributors` that gets the statistics about contributions. An alternative meaning would be to get the list of contributors (using this url: https://developer.github.com/v3/repos/#list-contributors).

How do you want to make them co-exist?

One possibility is to make the existing function `contributor_stats` and this other meaning `contributors`. Another option would be to use multiple dispatch somehow.

**Comment by WestleyArgentum** [comment]
Sorry for the delay -- ended up changing the stats version to `contributor_stats` in #24
