### ISSUE TITLE
can't use Github packge?

### ISSUE THREAD

**Issue by sindhus** [WestleyArgentum/GitHub.jl#33]
I ran a `Pkg.update()` and then did...

```
julia> Pkg.add("GitHub")
INFO: Nothing to be done

julia> using Github
Warning: replacing module GitHub
Warning: requiring "Github" did not define a corresponding module.

julia> using Github
Warning: requiring "Github" did not define a corresponding module.
```

What am I doing wrong?
Thanks!

**Comment by WestleyArgentum** [comment]
Hmm, did you previously have a copy of GitHub installed / had you already run `using GitHub`? Seems like, based on the output, there was already a module `GitHub` when you did `using Github`, and that the uppercase - lowercase switch confused it.

If you start a new julia session and do `using GitHub` (uppercase G and uppercase H), does it work?

**Comment by sindhus** [comment]
Oops! i am so blind, it's the camel casing of the package name! thanks!

**Comment by WestleyArgentum** [comment]
No worries!
