### ISSUE TITLE
Hasn't been updated for recent changes in Requests

### ISSUE THREAD

**Issue by IainNZ** [WestleyArgentum/GitHub.jl#35]
e.g. in Repo code, it still tries to do `Repo(JSON.parse(r.data))`. I think `Repo(Requests.json(r))` is the new way. Do you want a PR?

**Comment by WestleyArgentum** [comment]
Sorry, just saw this -- I'll have time to fix it this evening. PRs are always welcome, but I'm hardly in a position to ask for them given that the few tests that exist are commented out :)

**Comment by WestleyArgentum** [comment]
Should be fixed on master, will merge metadata tag when the tests there pass. Let me know if you have any more problems!
