### ISSUE TITLE
Creating issues?

### ISSUE THREAD

**Issue by IainNZ** [WestleyArgentum/GitHub.jl#8]
First of all, great work, love the package.

I wanted to know if creating issues through the API is coming any time soon? If not I could try to make a PR.

**Comment by WestleyArgentum** [comment]
I think this was resolved? Did you end up using this in PackageEvaluator to file issues?

This could be better documented still, but I'm closing in favor of #28

**Comment by IainNZ** [comment]
I ended up doing it manually
https://github.com/IainNZ/packages.julialang.org/blob/395ff8db8bf3b2fdab411db23f76bb42d3e43dd3/script/file_issues.jl#L93-L101
but if/when I refactor, I'll shift over.
